import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../constants";
const { width, height } = Dimensions.get('window')

export default StyleSheet.create({
    container:{
        flex: 1,
        backgroundColor: COLORS.white,
        paddingVertical: height * .02,
        paddingHorizontal: width * .04,
    },
    search:{
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:COLORS.white,
        elevation:5,
        borderRadius:10,
    },
    searchIcon:{
        width: width * .05,
        height: height * .025,
    },
    Btn:{
        width: width * .12,
        height: height * .06,
        alignItems:'center',
        justifyContent:'center',
    },
   
    searchText:{
        fontFamily: 'Poppins Regular 400',
        fontSize: 14,
        lineHeight: 15,
        color: COLORS.black, 
        width: width * .65,
        height: height * .06, 
        padding:0,
        paddingLeft: width * .04,
    },
    row:{
        flexDirection: 'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    adjustBtn:{
        width: width * .12,
        height: height * .06,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,
        backgroundColor:COLORS.blue2,
    },
    productContainer:{
        marginVertical: height * .03,
    },
    imageBox:{
        width: width * .92,
        height: height * .18, 
        borderRadius:8, 
        overflow:'hidden',
    },
    product_cover:{
        width: width * .92,
        height: height * .18,
    },
    contentBox:{
        marginVertical: height * .02,
    },
    title:{
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 16,
        lineHeight: 18,
        color: COLORS.black2,
    },
    locationRow:{
        flexDirection: 'row',
        alignItems:'center',
        marginVertical: height * .003,
    },
    location1:{
        width: width * .032,
        height: height * .025,
        marginRight: width * .01,
    },
    location:{
        width: width * .06,
        height: height * .03,
    },
    spotify:{
        fontFamily: 'Poppins Medium 500',
        fontSize: 12,
        lineHeight: 16,
        color: COLORS.black2,
    },
    text:{
        fontFamily: 'Poppins Medium 500',
        fontSize: 12,
        lineHeight: 16,
        color: '#C8C0C0',
    },
    star: {
        width: width * .05,
        height: height * .025,
        marginLeft: width * .01,
    },
    rating: {
        fontFamily: 'Poppins Bold 700',
        fontSize: 13,
        lineHeight: 15,
        marginBottom:1,
        marginRight: width * .01,
        color: COLORS.black2,
    },
    rupey:{
        fontSize: 16,
        lineHeight: 20,
        color: COLORS.black,
        marginHorizontal: width * .017,
    },
    btnRow:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    buttons:{
        width: width * .2,
        height: height * .08,
        alignItems:'center',
        justifyContent:'center',
    
    },
    callBox:{
        width: width * .08,
        height: height * .04,
        borderRadius: 50,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:COLORS.white,
        elevation:3,
    },
    call:{
        width: width * .06,
        height: height * .03,
    },
    whatsapp:{
        width: width * .09,
        height: height * .045,
    },
    location2:{
        width: width * .08,
        height: height * .04,
    },
    share1:{
        width: width * .08,
        height: height * .04,
        tintColor:COLORS.blue2,
    },
    buttonText:{
        fontFamily: 'Poppins Medium 500',
        fontSize: 10,
        lineHeight: 16,
        color: '#989898',
        marginTop:3,
    },
    enquiryBtn:{
        height: height * .05,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        borderWidth:1,
        borderColor:COLORS.blue2,
        borderRadius:5,
        marginHorizontal: width * .04,
        marginVertical: height * .015,
    },
    enquiryBtnTxt:{
        fontFamily: 'Poppins Bold 700',
        fontSize: 14,
        lineHeight: 18,
        marginBottom:-3,
        color: COLORS.blue2,
    },
    photoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: height * .01,
    },
    photos: {
        width: width * .3,
        height: height * .15,
    },
    photoBox: {
        width: width * .3,
        height: height * .15,
        marginHorizontal: width * .02,
        borderRadius: 7,
        overflow:'hidden',
    },
    title1:{
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 14,
        lineHeight: 18,
        color: '#7D7D7D',
        marginVertical: height * .005,
        marginLeft: width * .08,
    },
    timeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent:'space-between',
        marginVertical: height * .01,
        marginHorizontal: width * .1,
    },
    clock:{
        width: width * .06,
        height: height * .027,
        marginRight: width * .01,
        tintColor: '#6A6A6A',
    },
    txt:{
        fontFamily: 'Poppins Regular 400',
        fontSize: 12,
        lineHeight: 16,
        color: '#6A6A6A',
    },
    smallBtnRow:{
        flexDirection:'row',
        alignItems:'center',

    },
    smallBtn:{
        width: width * .27,
        height: height * .06,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:COLORS.white,
        borderRadius:10,
        elevation:2,
        marginHorizontal: width * .02,
    },
    smallBtnText:{
        fontFamily: 'Poppins Medium 500',
        fontSize: 12,
        lineHeight: 16,
        color: '#6A6A6A',
        marginTop:3,
    },
    headings:{
        fontFamily: 'Poppins Medium 500',
        fontSize: 16,
        lineHeight: 20,
        color: COLORS.black2,
        marginVertical: height * .01,
    },
    dot:{
        width:7,
        height: 7,
        borderRadius: 50,
        backgroundColor: COLORS.black,
        marginTop: 5,
        marginRight: width * .02,
    },
    descriptionRow:{
        flexDirection:'row',
        marginVertical: height * .005,
    },
    description:{
        fontFamily: 'Poppins Regular 400',
        fontSize: 13,
        lineHeight: 20,
        color: '#6A6A6A',
    },
    Box:{
        marginTop: height * .02,
    },
    experienceRow:{
        flexDirection:'row',
        alignItems:'center',
    },
    checkBox:{
        width: width * .07,
        height: height * .035,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:COLORS.green,
        borderRadius:50,
        marginRight: width * .02,
    },
    check:{
        width: width * .03,
        height: height * .015,
    },
    services:{
        width: width * .5,
        fontFamily: 'Poppins Medium 500',
        fontSize: 13,
        lineHeight: 18,
        color: '#252B42',
        marginTop: height * .002,
    },

    btn:{
        width: width * .34,
        height: height * .07,
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:COLORS.white,
        borderWidth:1,
        borderColor:'#E1E1E1',
    },
    btnTxt:{
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 14,
        lineHeight: 18,
        color: COLORS.black2,
        marginTop:3,
    },
    ModalContainer:{
        justifyContent: 'flex-start',
        alignItems:'flex-end',
    },
    sort:{
        width: width * .04,
        height: height * .02,
    },
    filter:{
        width: width * .04,
        height: height * .021,
    },
    sortIconBox:{
        width: width * .06,
        height: height * .03,
        alignItems:'center',
        justifyContent:'center',
        marginHorizontal: width * .03,
    },
})